name: build gateway single image as docker

on:
  push:
    branches: alpine_base_image

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to push on docker hub'
        required: true

env:
  IMAGE_NAME: 'ghcr.io/wirepas/gateway/single_image'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set tag for push to branch
        if: github.event_name == 'push'
        run: echo "TAG1=$IMAGE_NAME:edge" >> $GITHUB_ENV

      - name: Set tag for manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: echo "TAG1=$IMAGE_NAME:${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Login to GH container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/single_image/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          build-args: GATEWAY_BUILD_SHA1= ${{ github.sha }}
          tags: |
            ${{ env.TAG1 }}
